import type { Database } from './database.types';

type Rule = Database['public']['Tables']['rules']['Row'];

export type Tool = 'cursor' | 'claude_code' | 'copilot' | 'windsurf';

const TOOL_NAMES: Record<Tool, string> = {
  cursor: 'Cursor',
  claude_code: 'Claude Code',
  copilot: 'GitHub Copilot',
  windsurf: 'Windsurf',
};

const FILENAMES: Record<Tool, string> = {
  cursor: '.cursorrules',
  claude_code: 'CLAUDE.md',
  copilot: '.github/copilot-instructions.md',
  windsurf: '.windsurfrules',
};

export interface BundleOptions {
  tool: Tool;
  rules: Rule[];
  maxRules?: number;
}

/**
 * Generate bundle content for selected rules
 */
export function generateBundle({ tool, rules, maxRules = 25 }: BundleOptions): string {
  // Dedupe by ID and cap at maxRules
  const uniqueRules = Array.from(
    new Map(rules.map((rule) => [rule.id, rule])).values()
  ).slice(0, maxRules);

  const toolName = TOOL_NAMES[tool];
  const date = new Date().toISOString().split('T')[0];
  const count = uniqueRules.length;

  // Generate header
  const header = `# ${toolName} Rules
# Generated by RuleKit (rulekit.ttfw.io)
# Generated: ${date}
#
# Paste this file in your project root.
# ${count} rule(s) included.

`;

  // Generate body
  const body = uniqueRules
    .map((rule) => {
      return `## ${rule.title}

${rule.content}

---`;
    })
    .join('\n\n');

  return header + body;
}

/**
 * Get filename for a tool
 */
export function getFilename(tool: Tool): string {
  return FILENAMES[tool];
}

/**
 * Download bundle as file
 */
export function downloadBundle(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy bundle to clipboard
 */
export async function copyToClipboard(content: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(content);
  } catch (err) {
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = content;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.select();
    document.execCommand('copy');
    document.body.removeChild(textArea);
  }
}
