// This file will be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/lib/database.types.ts
//
// For now, this is a placeholder. After setting up your Supabase project,
// generate the types using the command above.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          github_id: string
          github_username: string
          github_avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          github_id: string
          github_username: string
          github_avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          github_id?: string
          github_username?: string
          github_avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      rules: {
        Row: {
          id: string
          title: string
          description: string | null
          content: string
          category: string | null
          tags: string[] | null
          tools: string[]
          task_types: string[]
          stacks: string[] | null
          content_hash: string
          upvotes: number
          downvotes: number
          verified_upvotes: number
          verified_downvotes: number
          status: 'pending' | 'approved' | 'rejected'
          created_by: string | null
          created_at: string
          updated_at: string
          fts: unknown
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          content: string
          category?: string | null
          tags?: string[] | null
          tools?: string[]
          task_types?: string[]
          stacks?: string[] | null
          content_hash?: string
          upvotes?: number
          downvotes?: number
          verified_upvotes?: number
          verified_downvotes?: number
          status?: 'pending' | 'approved' | 'rejected'
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          content?: string
          category?: string | null
          tags?: string[] | null
          tools?: string[]
          task_types?: string[]
          stacks?: string[] | null
          content_hash?: string
          upvotes?: number
          downvotes?: number
          verified_upvotes?: number
          verified_downvotes?: number
          status?: 'pending' | 'approved' | 'rejected'
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      votes: {
        Row: {
          id: string
          rule_id: string
          user_id: string | null
          identity_hash: string | null
          vote_type: 'upvote' | 'downvote'
          created_at: string
        }
        Insert: {
          id?: string
          rule_id: string
          user_id?: string | null
          identity_hash?: string | null
          vote_type: 'upvote' | 'downvote'
          created_at?: string
        }
        Update: {
          id?: string
          rule_id?: string
          user_id?: string | null
          identity_hash?: string | null
          vote_type?: 'upvote' | 'downvote'
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      cast_vote: {
        Args: {
          p_rule_id: string
          p_user_id?: string | null
          p_identity_hash?: string | null
          p_vote_type: string
        }
        Returns: Json
      }
      claim_pending_rules: {
        Args: {
          p_user_id: string
          p_limit?: number
        }
        Returns: {
          id: string
          title: string
          description: string | null
          content: string
          category: string | null
          tags: string[] | null
          created_at: string
        }[]
      }
      match_rules: {
        Args: {
          p_query: string
          p_limit?: number
          p_category?: string | null
          p_tags?: string[] | null
        }
        Returns: {
          id: string
          title: string
          description: string | null
          content: string
          category: string | null
          tags: string[] | null
          status: string
          created_at: string
          rank: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
